'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
require("core-js/es6/symbol");
require("core-js/es6/object");
require("core-js/es6/function");
require("core-js/es6/parse-int");
require("core-js/es6/parse-float");
require("core-js/es6/number");
require("core-js/es6/math");
require("core-js/es6/string");
require("core-js/es6/date");
require("core-js/es6/array");
require("core-js/es6/map");
require("core-js/es6/weak-map");
require("core-js/es6/set");
require("classlist.js");
require("core-js/es6/reflect");
require("core-js/es7/reflect");
require("zone.js/dist/zone");
require("rxjs/add/observable/throw");
require("rxjs/add/observable/forkJoin");
require("rxjs/add/operator/filter");
require("rxjs/add/operator/catch");
require("rxjs/add/operator/startWith");
require("rxjs/add/operator/do");
require("rxjs/add/operator/map");
//# sourceMappingURL=polyfills.js.map